Repository adavijit/BlogMan, pull requests merged in 2020-03, with the labels that each got.

#66 Fixed User model index error
  back-end/src/models/User.js
Labels: easy, gssoc20

#43 Modified login and signup page UI
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Login/index.jsx
  front-end/src/components/Register/index.jsx
  front-end/src/styles/index.css
  front-end/src/utils/constants.js
Labels: design, easy, gssoc20

#68 Added quiz section wireframe
  Wireframes/Quiz section Wireframe.png
  front-end/public/wire-frame/Quiz section Wireframe.png
Labels: design, gssoc20, medium

#73 Added udemy api for fetching courses
  back-end/.env
  back-end/package-lock.json
  back-end/package.json
  back-end/src/routes/api/courses.js
  back-end/src/routes/api/index.js
Labels: gssoc20, medium

#67 Google books api query feature added in the back-end
  back-end/package-lock.json
  back-end/package.json
  back-end/src/routes/api/books.js
  back-end/src/routes/api/index.js
Labels: API, gssoc20, medium

#75 Fixed axios not found error
  front-end/src/components/Login/index.jsx
  front-end/src/components/Register/index.jsx
Labels: bug, easy, gssoc20

#78 Fixed npm install error in backend
  back-end/package-lock.json
Labels: beginner, gssoc20

#81 Changed backend and frontend according to new user model
  back-end/src/routes/api/users.js
  front-end/src/components/Login/index.jsx
  front-end/src/components/Register/index.jsx
Labels: gssoc20, medium

#70 Book wireframe
  Wireframes/wireframe_book/Screenshot (57).png
  Wireframes/wireframe_book/wireframe_book.xd
Labels: design, gssoc20, medium

#83 Issue #56 Resolved: Created the "Our Team" section for BlogMan
  Wireframes/Our Team.png
  front-end/public/wire-frame/Our Team.png
Labels: easy, gssoc20

#93 Updating user wireframe
  front-end/public/wire-frame/User_Profile/1.png
  front-end/public/wire-frame/User_Profile/2.png
  front-end/public/wire-frame/User_Profile/3.png
  front-end/public/wire-frame/User_Profile/4.png
Labels: gssoc20, hard

#94 Closes issue #57
  front-end/public/wire-frame/Book Suggestion.png
Labels: gssoc20, medium

#96 Fixed 79
  back-end/package-lock.json
  back-end/package.json
  back-end/server.js
  back-end/src/models/User.js
  back-end/src/routes/api/books.js
  back-end/src/routes/api/courses.js
  back-end/src/routes/api/users.js
  back-end/src/routes/createController.js
  back-end/src/utils/jwt.js
  back-end/src/validators/auth.js
  front-end/src/components/Login/index.jsx
  front-end/src/components/Register/index.jsx
  front-end/src/services/http.js
Labels: gssoc20, hard

#97 API guidelines updated in Readme
  README.md
Labels: easy, gssoc20

#101 contributors default
  front-end/src/components/Contributors/Contributors.jsx
Labels: easy, gssoc20

#103 Closes issue #46
  front-end/public/wire-frame/QnA Section.fig
  front-end/public/wire-frame/QnA Section.png
Labels: gssoc20, medium

#105 Created wireframe for quiz section-SUBJECTIVE #Issue 53
  Wireframes/Quiz_Subjective .png
  front-end/public/wire-frame/Quiz_Subjective .png
Labels: gssoc20, medium

#104 Added frontend validators
  front-end/src/components/Login/index.jsx
  front-end/src/components/Register/index.jsx
  front-end/src/validators/auth.js
  front-end/src/validators/index.js
Labels: beginner, gssoc20

#107 Wireframe for particular QnA
  Wireframes/Wireframe for particular QnA.png
Labels: gssoc20, medium

#110 Solves issue: #52
  front-end/public/wire-frame/NUMERICAL.fig
  front-end/public/wire-frame/NUMERICAL.png
Labels: gssoc20, medium

#111 Added youtube api route
  back-end/.env
  back-end/.gitignore
  back-end/package-lock.json
  back-end/package.json
  back-end/src/routes/api/courses.js
Labels: gssoc20, hard

#113 Update readme
  README.md
Labels: easy, gssoc20

#112 #54 Idea Suggestion
  New_Ideas/new_idea.txt
Labels: easy, gssoc20

#116 Separated controllers and routes
  back-end/src/controllers/api/books.js
  back-end/src/controllers/api/courses.js
  back-end/src/controllers/api/users.js
  back-end/src/controllers/createController.js
  back-end/src/routes/api/books.js
  back-end/src/routes/api/courses.js
  back-end/src/routes/api/users.js
Labels: gssoc20, medium

#122 Changed google books API URL
  back-end/src/routes/api/books.js
Labels: easy, gssoc20

#121 Dark theme for blogman - #72 blogman dark theme 3
  dark theme website/css/style.css
  dark theme website/dark_theme_3.html
  dark theme website/img/img-4.jpg
  dark theme website/img/img-5.jpg
  dark theme website/img/img-6.jpg
  dark theme website/js/index.js
Labels: gssoc20, medium

#124 Added Google oauth
  back-end/.env
  back-end/auth/auth.js
  back-end/package-lock.json
  back-end/package.json
  back-end/server.js
  front-end/src/components/Login/index.jsx
Labels: gssoc20, hard

#123 Added public chat functionality
  back-end/.gitignore
  back-end/package-lock.json
  back-end/package.json
  back-end/server.js
  back-end/src/controllers/api/chat.js
  back-end/src/controllers/socket/controllers.js
  back-end/src/controllers/socket/index.js
  back-end/src/middlewares/addUser.js
  back-end/src/middlewares/auth.js
  back-end/src/middlewares/init.js
  back-end/src/models/Chat.js
  back-end/src/models/Message.js
  back-end/src/routes/api/chat.js
  back-end/src/routes/api/index.js
  back-end/src/utils/jwt.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/App/index.jsx
  front-end/src/components/ChatRoom/addChat.jsx
  front-end/src/components/ChatRoom/chatList.jsx
  front-end/src/components/ChatRoom/chatMessage.jsx
  front-end/src/components/ChatRoom/index.jsx
  front-end/src/components/ChatRoom/style.scss
  front-end/src/components/Common/Navbar.jsx
  front-end/src/components/Home/index.jsx
  front-end/src/components/index.js
  front-end/src/services/chat.js
  front-end/src/services/http.js
Labels: gssoc20, hard

#130 Github Auth
  back-end/auth/auth.js
  back-end/package-lock.json
  back-end/package.json
  back-end/server.js
  back-end/src/routes/api/githubAuth.js
  back-end/src/routes/api/googeAuth.js
  front-end/src/components/Login/index.jsx
  package-lock.json
Labels: gssoc20, hard

#133 Added profanity checker on text messages in chat and fixed package-lock.json error.
  back-end/package-lock.json
  back-end/package.json
  back-end/src/controllers/api/chat.js
Labels: gssoc20, hard

#167 Fixed google oauth, added .env.example file
  back-end/.env.example
  back-end/auth/auth.js
  back-end/src/controllers/api/users.js
  back-end/src/models/User.js
  back-end/src/routes/api/users.js
  back-end/src/validators/auth.js
  front-end/.env
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Login/index.jsx
  front-end/src/components/Register/index.jsx
  front-end/src/services/user.js
Labels: gssoc20, hard

#163 Solves issue #55
  Wireframes/ParticularCourse.fig
  Wireframes/ParticularCourse.png
  Wireframes/wireframe_book/ParticularBook.fig
  Wireframes/wireframe_book/ParticularBook.png
  Wireframes/wireframe_book/Screenshot (57).png
  Wireframes/wireframe_book/wireframe_book.xd
  front-end/public/wire-frame/ParticularBook.png
  front-end/public/wire-frame/ParticularCourse.fig
  front-end/public/wire-frame/ParticularCourse.png
Labels: gssoc20, hard

#174 IssueFixed: #154 , Recommender Package with Content-Based-Recommender Module
  back-end/package-lock.json
  back-end/package.json
  back-end/src/routes/api/blog.js
Labels: gssoc20, medium
